# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /cc-react-admin-ui/

# Installing dependencies
COPY public/ /rcc-react-admin-ui/public
COPY src/ /cc-react-admin-ui/src
COPY package.json /cc-react-admin-ui/

RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD ["npm", "start"]